#!/usr/bin/env python3

import sys
from Bio import SeqIO
from argparse import ArgumentParser, RawDescriptionHelpFormatter

DESCRIPTION = """Wrapper for ncbi-datasets-cli"""
parser = ArgumentParser(
    description=DESCRIPTION, formatter_class=RawDescriptionHelpFormatter
)
parser.add_argument("faa", help="fasta file.")

args = parser.parse_args()
FAA = args.faa

records = SeqIO.parse(FAA, "fasta")
count = SeqIO.write(records, sys.stdout, "tab")
print(f"Converted {count} fasta records to tsv.", file = sys.stderr)
